In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score','lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [5]:
! pip install tensorflow
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense


[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


     ---------------------------------------- 0.0/41.7 kB ? eta -:--:--
     --------------------------- ---------- 30.7/41.7 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 41.7/41.7 kB 684.8 kB/s eta 0:00:00
  Using cached certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
   ---------------------------------------- 0.0/350.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/350.8 MB 1.3 MB/s eta 0:04:35
   ---------------------------------------- 0.0/350.8 MB 653.6 kB/s eta 0:08:57
   ---------------------------------------- 0.0/350.8 MB 653.6 kB/s eta 0:08:57
   ---------------------------------------- 0.0/350.8 MB 653.6 kB/s eta 0:08:57
   ---------------------------------------- 0.1/350.8 MB 328.6 kB/s eta 0:17:48
   ---------------------------------------- 0.1/350.8 MB 532.5 kB/s eta 0:10:59
   ---------------------------------------- 0.2/350.8 MB 615.9 kB/s eta 0:09:30
   ---------------------------------------- 0.2/350.8 MB 615.9 kB/s eta

In [6]:
model = Sequential()
model.add(Dense(2,activation='linear', input_dim=2))
model.add(Dense(1,activation='linear'))

c:\Users\MohitSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[-1.1290933 , -0.38000548],
        [ 0.43368483, -0.19907176]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0873001 ],
        [-0.28463686]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
## Assigned - weight as 0.1 and biases as 0
new_weights = [np.array([[0.1,0.1],[0.1,0.1]], dtype= np.float32),np.array([0.,0.], dtype=np.float32), np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0.1], dtype=np.float32)]

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [14]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [15]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 26.8796  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.5499 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.2225 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.9164 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.5666
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.1998 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.8372 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.5016 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.1079 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.6926 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.2947 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.8636 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.4755 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.0018 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.5849 
Epoch 16/75
4/4 ━━