# Numpy
Numpy is the core python library used for numerical opeartions and arrays
- Numpy is imported using `import numpy as np`
- faster than python lists , 50 times you can say
- used heavily in AI, ML, data science and plotting

In [47]:
import numpy as np
print(np.__version__)

2.4.4


# Creating Arrays
`np.array()` is used to creat Numpy arrays
- 1D array = simple list
- 2D array = matrix
- 3D array = collection of matrices

In [48]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

print(arr1)
print(arr2)
print(arr3)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Dimensions, shape and size
- ndim - gives the number of dimensions
- shape - gives size in each dimensions
- size - gives total number of elements
for eg: for shape(2,3):
- 2 rows
- 3 columns


In [49]:
arr = np.array([[1,2,3],[4,5,6]])

print("Dimension:",arr.ndim)
print("Shape:",arr.shape)
print("Size:", arr.size)

Dimension: 2
Shape: (2, 3)
Size: 6


# Indexing
Indexing is used to access a specific element
- first index = row
- Second index = column
- Negative index starts from end

In [50]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr[0,1])
print(arr[1,-1])


2
6


In [51]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, -1])

2
6
10


# Slicing
Slicing is used to get multiple values from an array
- syntax : `arr[start: stop :step]`
- start - included
- stop - excluded
- step - means skipping

1st before comma represent the rows and second represent the columns and this is simple representation : ::2 in rows → take every 2nd row
: in columns → take all columns

In [52]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[:, ::2])
print(arr[0:2, 2])

[[ 1  3  5]
 [ 6  8 10]]
[3 8]


# Data types
Every Numpy array has a datatype, Common types are i:
- i = integer
- f = float
- s - string

In [53]:
arr = np.array([1,2,3], dtype='f')

print(arr)
print(arr.dtype)

[1. 2. 3.]
float32


# Converting Data Type on Existing Arrays
To change the data type of an existing array, is to make a copy of the array with the `astype() method`. The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.


In [54]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Copy bs View
- copy create seperate array
- view points to original array
- Important points : if original changes then copy does not changebut view changes

In [55]:
arr = np.array([1,2,3,4])

copy_arr = arr.copy()
view_arr = arr.view()

arr[0] = 100

print("Original:", arr)
print("Copy:", copy_arr)
print("View:", view_arr)

Original: [100   2   3   4]
Copy: [1 2 3 4]
View: [100   2   3   4]


# how to check if array owns its data
Every NumPy array has the attribute `base` that returns `None` if the array owns the data. Otherwise, the base  attribute refers to the original object. In easy way : The copy returns None. The view returns the original array.

In [56]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Shape of an Array
The shape of an array is the number of elements in each dimension.NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [57]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [58]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

# Reshape
`reshape()` changes the shape of the array without changing the data


In [59]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


# Reshaping in the 3d array

In [60]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
- Also The example above returns the original array, so it is a view. when we know the base then 

Unknown dimension : Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Iteration
What is this? Used to loop through all values of an array
Important Method:
- `np.nditer()` gives each scalar value one by one

In [63]:
arr = np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


Important points:
- : means all rows
- : ::2 means every 2nd column
- useful when you want to skip elements

In [64]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


# Enumerated Iteration using ndenumerate on 1D array
what is this?
`np.ndenumerate()` gives both:
- index
- value

In [65]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x) 
    # where idx represent row and x represnt column

(0,) 1
(1,) 2
(2,) 3


# Joining Arrays
what is this?
`concatenate()` join arrays.
Important points: 
- `axis=0` -> join row-wise
- `axis=1` -> join column-wise

In [66]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(np.concatenate((arr1, arr2), axis=0))
print(np.concatenate((arr1, arr2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Joining Arrays Using Stack Functions
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

# stacking
- Along with the rows : Numpy provides a helper function: `hstack()` to stack along rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

- Stacking Along Columns
NumPy provides a helper function: `vstack()`  to stack along columns.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

- Stacking Along Height (depth)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))







# splitting Arrays
what is this?
`array_split()` divides an array into parts.


In [67]:
arr = np.array([1,2,3,4,5,6])
print(np.array_split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [68]:
# Split the 2-D array into three 2-D arrays along columns.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

In [69]:
# An alternate solution is using hsplit() opposite of hstack()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)

# Searching
what is this? `where()` is used to find index positions

In [70]:
arr = np.array([10,20,30,20,50])
print(np.where(arr == 20))

(array([1, 3]),)


In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


# Search sorted
searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)


Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

- multiple values
Find the indexes where the values 2, 4, and 6 should be inserted:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

# Sorting: `sort()` arranges values in ascending order
arr = np.array([3,1,5,2,4])
print(np.sort(arr))

# Filtering:
what is this?
filtering selects elements based on True/ False values

In [72]:
arr = np.array([41,42,43,44])

mask = [True, False, True, False]

print(arr[mask])

[41 43]


In [75]:
# Boolean masking : Instead of manually writing True/False we can create condition directly
arr = np.array([10,20,30,40,50])
print(arr[arr > 25])

[30 40 50]


## Broadcasting

### What is this?
Broadcasting allows NumPy to perform operations on arrays of different shapes.

arr = np.array([1,2,3])

print(arr + 10)

## Matrix Operations

### What is this?
Useful in ML and linear algebra.

### Important Methods
- `np.dot()` -> matrix multiplication
- `.T` -> transpose


In [76]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a, b))
print(a.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


## Arange and Linspace

### What is this?
- `arange()` creates values with step
- `linspace()` creates fixed number of values


In [77]:
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## Random Numbers

### What is this?
Useful for ML datasets and random initialization.


In [79]:
print(np.random.randint(1,10))  # gives the integer value
print(np.random.rand(2,3))  # gives the float value

arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)

print(arr)

4
[[0.88483164 0.10302312 0.9376535 ]
 [0.82678107 0.7392729  0.97423343]]
[3 4 1 2 5]


In [ ]:
from numpy import random
x=random.randint(100, size=(5)) # this is used the size to get 5 integers form o to 100
x = random.randint(100, size=(3, 5)) # gives 2d 3 rows and 5 colums
x = random.choice([3, 5, 7, 9]) # pick one valyes from the list
x = random.choice([3, 5, 7, 9], size=(3, 5)) # for setting th limit you know     [[9 3 5 5 7] 
                                                                              #  [7 5 3 3 9] 
                                                                                 # [7 5 9 9 7]]
print(x)

[[3 9 5 7 5]
 [3 3 5 7 7]
 [5 3 5 3 7]]
