In [1]:
# creating matrix
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(A)
print(A.shape)   # (3, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [2]:
# utility functions 
# Zero matrix
Z = np.zeros((3, 4))       # 3 rows, 4 columns, all zeros
print(Z)

# Ones matrix
O = np.ones((2, 3))        # all ones
print(O)

# Identity matrix (square matrix, diagonal = 1)
I = np.eye(4)              # 4×4 identity
print(I)

# Diagonal matrix from a vector
d = np.diag([1, 2, 3, 4])  # puts values on the diagonal
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [3]:
# Random matrices
# Uniform distribution [0, 1)
R1 = np.random.rand(3, 3)

# Standard normal distribution (mean=0, std=1)
R2 = np.random.randn(3, 3)

# Random integers
R3 = np.random.randint(0, 10, size=(3, 3))   # values in [0, 10)

# For reproducibility — always set seed in ML experiments
np.random.seed(42)
W = np.random.randn(3, 4)   # Weight matrix for a layer
print(W)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]


In [4]:
# matrix properties
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.shape)   # (2, 3)  → 2 rows, 3 columns
print(A.size)    # 6       → total elements
print(A.ndim)    # 2       → 2 dimensions
print(A.dtype)   # int64

# Accessing rows and columns
print(A[0])      # [1 2 3]  → first row
print(A[:, 1])   # [2 5]    → second column
print(A[1, 2])   # 6        → element at row 1, col 2

(2, 3)
6
2
int64
[1 2 3]
[2 5]
6


In [5]:
# Transpose of a Matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.shape)     # (2, 3)
print(A.T.shape)   # (3, 2)
print(A.T)
# [[1 4]
#  [2 5]
#  [3 6]]

# Equivalent
print(np.transpose(A))

(2, 3)
(3, 2)
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [6]:
# Matrix opeations
# Addition and subtraction
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)
# [[ 6  8]
#  [10 12]]

print(A - B)
# [[-4 -4]
#  [-4 -4]]

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [7]:
# Scalar Multiplication
A = np.array([[1, 2], [3, 4]])

print(3 * A)
# [[ 3  6]
#  [ 9 12]]

print(A / 2)
# [[0.5 1. ]
#  [1.5 2. ]]

[[ 3  6]
 [ 9 12]]
[[0.5 1. ]
 [1.5 2. ]]


In [8]:
# Element wise multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise (NOT matrix multiplication)
C = A * B
print(C)
# [[ 5 12]
#  [21 32]]

[[ 5 12]
 [21 32]]


To multiply A × B:

A has shape (m × k)
B has shape (k × n)
Result has shape (m × n)
The inner dimensions must match (both equal to k).

In [9]:
# matrix multiplicatiom
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # shape (3, 2)

B = np.array([[7, 8, 9],
              [10, 11, 12]])  # shape (2, 3)

# Method 1: np.dot()
C = np.dot(A, B)
print(C)
# [[ 27  30  33]
#  [ 61  68  75]
#  [ 95 106 117]]
print(C.shape)   # (3, 3)

# Method 2: @ operator (preferred)
C2 = A @ B
print(np.array_equal(C, C2))   # True

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
(3, 3)
True


In [10]:
# Element wise vs Matrix multiplicatio
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print("Element-wise (A * B):\n", A * B)
# [[ 2  0]
#  [ 3 12]]

print("Matrix multiply (A @ B):\n", A @ B)
# [[ 4  6]
#  [10 12]]

Element-wise (A * B):
 [[ 2  0]
 [ 3 12]]
Matrix multiply (A @ B):
 [[ 4  6]
 [10 12]]


In [11]:
# Transpose
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.T)       # or np.transpose(A)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
# identity matrix
I = np.eye(3)
print(I)
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

A = np.array([[2, 3], [1, 4]])
print(A @ np.eye(2))   # Returns A unchanged

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2. 3.]
 [1. 4.]]


In [13]:
# diagonal matrices
# Extract diagonal from a matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

diag_vals = np.diag(A)
print(diag_vals)   # [1 5 9]  ← main diagonal

# Create a diagonal matrix from values
D = np.diag([3, 7, 2])
print(D)
# [[3 0 0]
#  [0 7 0]
#  [0 0 2]]

# Trace: sum of diagonal elements
print(np.trace(A))   # 15  (= 1 + 5 + 9)


[1 5 9]
[[3 0 0]
 [0 7 0]
 [0 0 2]]
15


In [14]:
# symmetrix matrix : 
A = np.array([[1, 2, 3],
              [2, 5, 6],
              [3, 6, 9]])

is_symmetric = np.array_equal(A, A.T)
print(is_symmetric)   # True

True


In [15]:
#  Determinant, Inverse & Rank
# For 2×2: det([[a,b],[c,d]]) = ad - bc

A = np.array([[3, 1],
              [2, 4]])

det = np.linalg.det(A)
print(f"det(A) = {det:.2f}")   # det(A) = 10.00

# 3×3 example
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
print(f"det(B) = {np.linalg.det(B):.2f}")   # det(B) = 1.00

det(A) = 10.00
det(B) = 1.00


In [16]:
# matrix inverse
A = np.array([[3.0, 1.0],
              [2.0, 4.0]])

A_inv = np.linalg.inv(A)
print("Inverse:\n", A_inv)

# Verify: A × A⁻¹ should be Identity
product = A @ A_inv
print("A × A_inv:\n", np.round(product, 10))
# [[1. 0.]
#  [0. 1.]]  ← Identity matrix ✓

Inverse:
 [[ 0.4 -0.1]
 [-0.2  0.3]]
A × A_inv:
 [[1. 0.]
 [0. 1.]]


In [17]:
# matrix rank
# Full rank matrix
A = np.array([[1, 0], [0, 1]])
print(np.linalg.matrix_rank(A))   # 2 (full rank)

# Rank-deficient matrix (rows are dependent)
B = np.array([[1, 2, 3],
              [2, 4, 6],   # ← 2 × row 0
              [0, 1, 2]])
print(np.linalg.matrix_rank(B))   # 2 (not 3, because row 1 = 2 × row 0)

2
2


# linear system of equations
A = [[3, 1],    x = [x],    b = [9]
     [2, 4]]        [y]         [22]

In [18]:
A = np.array([[3.0, 1.0],
              [2.0, 4.0]])
b = np.array([9.0, 22.0])

x = np.linalg.solve(A, b)
print(x)   # [2. 3.]  → x=2, y=3

# Verify: Ax should equal b
print(np.allclose(A @ x, b))   # True

[1.4 4.8]
True


In [19]:
# when the system has no solutions
# Singular matrix (det = 0) → no unique solution
A_singular = np.array([[1.0, 2.0],
                        [2.0, 4.0]])   # row 2 = 2 × row 1
b = np.array([3.0, 6.0])

try:
    x = np.linalg.solve(A_singular, b)
except np.linalg.LinAlgError as e:
    print(f"Error: {e}")   # Singular matrix

Error: Singular matrix


In [20]:
# Eigen value and Eigen vectors
A = np.array([[4.0, 1.0],
              [2.0, 3.0]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
# [5. 2.]

print("Eigenvectors (columns):\n", eigenvectors)
# Each COLUMN is an eigenvector
# [[ 0.707  -0.447]
#  [ 0.707   0.894]]

# Verify: A @ v = λ × v
v1 = eigenvectors[:, 0]   # first eigenvector
lambda1 = eigenvalues[0]  # first eigenvalue
print(np.allclose(A @ v1, lambda1 * v1))   # True ✓

Eigenvalues: [5. 2.]
Eigenvectors (columns):
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
True


In [21]:
# Dataset: 5 students, 3 features (math, science, english scores)
X = np.array([[85, 92, 78],
              [70, 65, 80],
              [90, 88, 95],
              [60, 72, 68],
              [75, 80, 85]])
# Shape: (5, 3) — 5 samples, 3 features

print(f"Samples: {X.shape[0]}, Features: {X.shape[1]}")

Samples: 5, Features: 3
