In [1]:
import numpy as np

In [2]:
# 1D array — the standard vector
v = np.array([1, 2, 3, 4])
print(v)        # [1 2 3 4]
print(type(v))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# Row vector — shape (1, n)
row = np.array([[1, 2, 3]])
print(row.shape)   # (1, 3)

# Column vector — shape (n, 1)
col = np.array([[1],
                [2],
                [3]])
print(col.shape)   # (3, 1)

(1, 3)
(3, 1)


In [4]:
# utility functions for creating vectors
# All zeros
zeros = np.zeros(5)
print(zeros)   # [0. 0. 0. 0. 0.]

# All ones
ones = np.ones(4)
print(ones)    # [1. 1. 1. 1.]

# Range of values (like Python's range)
r = np.arange(0, 10, 2)    # start=0, stop=10, step=2
print(r)       # [0 2 4 6 8]

# Evenly spaced values between two points
ls = np.linspace(0, 1, 5)  # 5 points from 0 to 1
print(ls)      # [0.   0.25 0.5  0.75 1.  ]

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [5]:
v = np.array([10, 20, 30, 40, 50])

print(v.shape)   # (5,)   → 1D with 5 elements
print(v.size)    # 5      → total number of elements
print(v.ndim)    # 1      → number of dimensions
print(v.dtype)   # int64  → data type of elements

(5,)
5
1
int64


In [6]:
# Reshaping Vectors :Reshaping changes the shape (structure) without changing the data (values).
v = np.array([1, 2, 3, 4, 5, 6])

# Convert 1D vector to column vector
col = v.reshape(6, 1)
print(col.shape)   # (6, 1)

# Convert 1D to row vector
row = v.reshape(1, 6)
print(row.shape)   # (1, 6)

# Use -1 to let NumPy infer one dimension
col2 = v.reshape(-1, 1)   # same as (6, 1)
row2 = v.reshape(1, -1)   # same as (1, 6)

(6, 1)
(1, 6)


In [7]:
#Flattening
matrix = np.array([[1, 2], [3, 4], [5, 6]])
flat = matrix.flatten()     # Always returns a copy
print(flat)  # [1 2 3 4 5 6]

flat2 = matrix.ravel()      # Returns a view when possible (more memory efficient)

[1 2 3 4 5 6]


In [12]:
# Addition and subtraction 
# a = [1, 2, 3]
# b = [4, 5, 6]
# a + b = [5, 7, 9]
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a - b)   # [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [13]:
# Scalar Multiplication
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])

print(a * b)     # [ 2  8 18]  ← element-wise multiply (NOT dot product)
print(a / b)     # [2. 2. 2.]
print(a % b)     # [0 0 0]
print(np.sqrt(a))# [1.414 2.    2.449]


[ 2  8 18]
[2. 2. 2.]
[0 0 0]
[1.41421356 2.         2.44948974]


In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Method 1: np.dot()
result1 = np.dot(a, b)
print(result1)   # 32

# Method 2: @ operator (preferred in modern Python)
result2 = a @ b
print(result2)   # 32

# Method 3: manual (slow — never use in practice)
result3 = np.sum(a * b)
print(result3)   # 32

32
32
32


In [15]:
# Linear regression prediction: y = w · x + b
weights = np.array([0.5, 1.2, -0.3])
features = np.array([2.0, 3.0, 1.0])
bias = 0.8

prediction = np.dot(weights, features) + bias
print(f"Prediction: {prediction:.2f}")   # Prediction: 4.10

# Similarity check
user_a = np.array([5, 3, 0, 1])   # ratings for 4 movies
user_b = np.array([4, 0, 4, 1])
similarity = np.dot(user_a, user_b)
print(f"Raw similarity: {similarity}")   # 22

Prediction: 5.10
Raw similarity: 21


In [16]:
# L1 Nor(Manhattan Norm)
v = np.array([3, -4, 0, 2])

l1 = np.linalg.norm(v, ord=1)
print(l1)   # 9.0  →  |3| + |-4| + |0| + |2| = 9

9.0


np → short name for NumPy
linalg → linear algebra module inside NumPy
norm(...) → function that computes the norm (length/size) of a vector or matrix
v → the vector you are passing
ord=1 → tells NumPy which type of norm to calculate

So ord stands for “order of the norm”.

In [17]:
# L2 Norm (Euclidean Norm)
l2 = np.linalg.norm(v)       # Default is L2
print(l2)   # 5.0  →  √(9 + 16) = √25 = 5

# Manual verification
manual = np.sqrt(np.sum(v**2))
print(manual)   # 5.0

5.385164807134504
5.385164807134504


In [18]:
# L∞ Norm (Max Norm)
v = np.array([3, -7, 2])
linf = np.linalg.norm(v, ord=np.inf)
print(linf)   # 7.0

7.0


ord=np.inf means:
compute the infinity norm (L∞ norm)
The infinity norm is defined as:
So first take absolute values:
∣3∣=3,∣−7∣=7,∣2∣=2
Now the vector becomes:
[3,7,2]
Then choose the largest value:
max(3,7,2)=7

# unit vector and normalizaiton 
# û = v / ||v||₂
Why Normalization Matters
Removes scale bias: A feature with values [0–1000] would dominate one with values [0–1]
Enables cosine similarity: Comparing directions rather than magnitudes
Faster convergence: Gradient descent behaves better with normalized inputs

In [19]:
v = np.array([3.0, 4.0])

# Normalize to unit vector
unit_v = v / np.linalg.norm(v)
print(unit_v)                       # [0.6 0.8]
print(np.linalg.norm(unit_v))       # 1.0  ← confirmed unit vector

# General normalization function
def normalize(vector):
    norm = np.linalg.norm(vector)
    if norm == 0:
        raise ValueError("Cannot normalize a zero vector!")
    return vector / norm

v = np.array([1.0, 2.0, 2.0])
print(normalize(v))   # [0.333 0.667 0.667]

[0.6 0.8]
1.0
[0.33333333 0.66666667 0.66666667]


In [20]:
# Angle between vectors
# cos(θ) = (a · b) / (||a|| × ||b||)
# θ = arccos(a · b / ||a|| × ||b||)

# Cosine Similarity
# Cosine similarity is just cos(θ) — it ranges from -1 to 1:

# cos(θ)	Meaning
# 1.0	Identical direction (0°)
# 0.0	Perpendicular (90°)
# -1.0	Opposite direction (180°)


a = np.array([1.0, 0.0, 1.0])
b = np.array([1.0, 1.0, 0.0])

# Cosine similarity
cos_sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(f"Cosine Similarity: {cos_sim:.4f}")   # 0.5000

# Angle in degrees
angle_rad = np.arccos(np.clip(cos_sim, -1.0, 1.0))  # clip for numerical safety
angle_deg = np.degrees(angle_rad)
print(f"Angle: {angle_deg:.2f}°")            # 60.00°


Cosine Similarity: 0.5000
Angle: 60.00°


In [21]:
# Two documents represented as word frequency vectors
doc1 = np.array([1, 1, 0, 1, 0])   # words: [python, data, java, science, cpp]
doc2 = np.array([1, 1, 1, 0, 0])

cos_sim = np.dot(doc1, doc2) / (np.linalg.norm(doc1) * np.linalg.norm(doc2))
print(f"Document similarity: {cos_sim:.4f}")   # 0.6667

# High similarity → documents discuss similar topics

Document similarity: 0.6667


## 9. 🔁 Broadcasting with Vectors
Broadcasting is NumPy's ability to perform operations on arrays of different shapes by automatically "stretching" the smaller array.

Rules (applied dimension by dimension, right to left):

If arrays differ in number of dimensions, prepend 1s to the smaller shape
Dimensions of size 1 are stretched to match the other
Shapes must be compatible (equal or one of them is 1)

In [22]:
# Scalar broadcast to vector
v = np.array([1, 2, 3])
print(v + 10)    # [11 12 13]  ← 10 is broadcast to [10, 10, 10]

# 1D broadcast with 2D
A = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)
b = np.array([10, 20, 30])  # shape (3,)  → broadcast as (1, 3) → (2, 3)

print(A + b)
# [[11 22 33]
#  [14 25 36]]

[11 12 13]
[[11 22 33]
 [14 25 36]]


In [24]:
# Column vs Row Broadcasting
col = np.array([[1],   # shape (3, 1)
                [2],
                [3]])
row = np.array([10, 20, 30])  # shape (3,) → (1, 3)

result = col + row
print(result)
# [[11, 21, 31],
#  [12, 22, 32],
#  [13, 23, 33]]
# shape: (3, 3)  ← outer sum!

[[11 21 31]
 [12 22 32]
 [13 23 33]]


a = np.array([1, 2, 3])      # shape (3,)
b = np.array([1, 2])         # shape (2,)

# ❌ Error: incompatible shapes
# a + b  → ValueError: operands could not be broadcast together with shapes (3,) (2,)

# ✅ Fix: make shapes compatible
b_col = b.reshape(2, 1)     # shape (2, 1)
a_row = a.reshape(1, 3)     # shape (1, 3)
result = b_col + a_row      # shape (2, 3) — valid outer sum